name: Dependabot
on: workflow_dispatch
jobs:
  nothing:
    steps:
      - run: echo ${{ github.actor }}
version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "npm"
    open-pull-requests-limit: 1
    versioning-strategy: widen

  - package-ecosystem: "npm"
    directory: "/api/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "npm"
    open-pull-requests-limit: 1
    versioning-strategy: widen
